title: Sudeep Maurya
description: Undergradate student \n Indian Institute of Science Education and Research, Mohali 
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  is_project_page: false
