title: Sudeep Maurya
insti: Indidan Institute of Science Education and Research, Mohali
major: Physics major, 3rd year
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  is_project_page: false
