title: Sudeep Maurya
description: BS-MS 
Indian Institute of Science Education and Research, Mohali (IISER-M)
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  is_project_page: false
