title: Sudeep Maurya
description: Indian Institute of Science Education and Research, Mohali
year: BS-MS, Physics major, 4th year
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  is_project_page: false
