title: Sudeep Maurya
description: Indian Institute of Science Education and Research, Mohali
year: BS-MS, Physics major, 4th year
contacts : ms21130@iisermohali.ac.in (Intstitute mail); sudeep.maurya9903@gmail.com (Personal mail)
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
github:
  is_project_page: false
